name: Check if builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.5.22307.18
    - name: Restore dependencies
      run: dotnet restore ./DotNetMicroserviceTemplate.sln
    - name: Build
      run: dotnet build --no-restore ./Service/Service.csproj
    - name: Test
      run: dotnet test --verbosity minimal